language: generic

os:
    - linux
    - osx

env:
    - HEAD=yes

sudo: false
dist: trusty

addons:
    apt:
        packages:
            - vim

install:
    - pip install vim-vint --upgrade

script:
    - vim --version
    - vint --version
    - vint .vimrc
    - ./setup.sh
    - vim +NeoBundleInstall +q

